<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        // Dapatkan mapping province code ke id
        $provinces = DB::table('province')->pluck('id', 'code');
        
        $cities = [
            // Aceh (11)
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Barat Daya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Besar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Jaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Singkil', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Tamiang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Tenggara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Aceh Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Bener Meriah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Bireuen', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Gayo Lues', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Nagan Raya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Pidie', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Pidie Jaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kabupaten Simeulue', 'type' => 'kabupaten'],
            ['province_id' => $provinces['11'], 'name' => 'Kota Banda Aceh', 'type' => 'kota'],
            ['province_id' => $provinces['11'], 'name' => 'Kota Langsa', 'type' => 'kota'],
            ['province_id' => $provinces['11'], 'name' => 'Kota Lhokseumawe', 'type' => 'kota'],
            ['province_id' => $provinces['11'], 'name' => 'Kota Sabang', 'type' => 'kota'],
            ['province_id' => $provinces['11'], 'name' => 'Kota Subulussalam', 'type' => 'kota'],

            // Sumatera Utara (12)
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Asahan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Batubara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Dairi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Deli Serdang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Humbang Hasundutan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Karo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Labuhanbatu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Labuhanbatu Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Labuhanbatu Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Langkat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Mandailing Natal', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Nias', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Nias Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Nias Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Nias Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Padang Lawas', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Padang Lawas Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Pakpak Bharat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Samosir', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Serdang Bedagai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Simalungun', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Tapanuli Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Tapanuli Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Tapanuli Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kabupaten Toba Samosir', 'type' => 'kabupaten'],
            ['province_id' => $provinces['12'], 'name' => 'Kota Binjai', 'type' => 'kota'],
            ['province_id' => $provinces['12'], 'name' => 'Kota Gunungsitoli', 'type' => 'kota'],
            ['province_id' => $provinces['12'], 'name' => 'Kota Medan', 'type' => 'kota'],
            ['province_id' => $provinces['12'], 'name' => 'Kota Padangsidempuan', 'type' => 'kota'],
            ['province_id' => $provinces['12'], 'name' => 'Kota Pematangsiantar', 'type' => 'kota'],
            ['province_id' => $provinces['12'], 'name' => 'Kota Sibolga', 'type' => 'kota'],
            ['province_id' => $provinces['12'], 'name' => 'Kota Tanjungbalai', 'type' => 'kota'],
            ['province_id' => $provinces['12'], 'name' => 'Kota Tebing Tinggi', 'type' => 'kota'],

            // Sumatera Barat (13)
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Agam', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Dharmasraya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Kepulauan Mentawai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Lima Puluh Kota', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Padang Pariaman', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Pasaman', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Pasaman Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Pesisir Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Sijunjung', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Solok', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Solok Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kabupaten Tanah Datar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['13'], 'name' => 'Kota Bukittinggi', 'type' => 'kota'],
            ['province_id' => $provinces['13'], 'name' => 'Kota Padang', 'type' => 'kota'],
            ['province_id' => $provinces['13'], 'name' => 'Kota Padangpanjang', 'type' => 'kota'],
            ['province_id' => $provinces['13'], 'name' => 'Kota Pariaman', 'type' => 'kota'],
            ['province_id' => $provinces['13'], 'name' => 'Kota Payakumbuh', 'type' => 'kota'],
            ['province_id' => $provinces['13'], 'name' => 'Kota Sawahlunto', 'type' => 'kota'],
            ['province_id' => $provinces['13'], 'name' => 'Kota Solok', 'type' => 'kota'],

            // Riau (14)
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Bengkalis', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Indragiri Hilir', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Indragiri Hulu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Kampar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Kepulauan Meranti', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Kuantan Singingi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Pelalawan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Rokan Hilir', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Rokan Hulu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kabupaten Siak', 'type' => 'kabupaten'],
            ['province_id' => $provinces['14'], 'name' => 'Kota Dumai', 'type' => 'kota'],
            ['province_id' => $provinces['14'], 'name' => 'Kota Pekanbaru', 'type' => 'kota'],

            // Jambi (15)
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Batanghari', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Bungo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Kerinci', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Merangin', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Muaro Jambi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Sarolangun', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Tanjung Jabung Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Tanjung Jabung Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kabupaten Tebo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['15'], 'name' => 'Kota Jambi', 'type' => 'kota'],
            ['province_id' => $provinces['15'], 'name' => 'Kota Sungai Penuh', 'type' => 'kota'],

            // Sumatera Selatan (16)
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Banyuasin', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Empat Lawang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Lahat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Muara Enim', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Musi Banyuasin', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Musi Rawas', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Musi Rawas Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Ogan Ilir', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Ogan Komering Ilir', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Ogan Komering Ulu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Ogan Komering Ulu Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Ogan Komering Ulu Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kabupaten Penukal Abab Lematang Ilir', 'type' => 'kabupaten'],
            ['province_id' => $provinces['16'], 'name' => 'Kota Lubuklinggau', 'type' => 'kota'],
            ['province_id' => $provinces['16'], 'name' => 'Kota Pagar Alam', 'type' => 'kota'],
            ['province_id' => $provinces['16'], 'name' => 'Kota Palembang', 'type' => 'kota'],
            ['province_id' => $provinces['16'], 'name' => 'Kota Prabumulih', 'type' => 'kota'],

            // Bengkulu (17)
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Bengkulu Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Bengkulu Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Bengkulu Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Kaur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Kepahiang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Lebong', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Mukomuko', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Rejang Lebong', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kabupaten Seluma', 'type' => 'kabupaten'],
            ['province_id' => $provinces['17'], 'name' => 'Kota Bengkulu', 'type' => 'kota'],

            // Lampung (18)
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Lampung Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Lampung Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Lampung Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Lampung Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Lampung Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Mesuji', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Pesawaran', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Pesisir Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Pringsewu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Tanggamus', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Tulang Bawang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Tulang Bawang Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kabupaten Way Kanan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['18'], 'name' => 'Kota Bandar Lampung', 'type' => 'kota'],
            ['province_id' => $provinces['18'], 'name' => 'Kota Metro', 'type' => 'kota'],

            // Kepulauan Bangka Belitung (19)
            ['province_id' => $provinces['19'], 'name' => 'Kabupaten Bangka', 'type' => 'kabupaten'],
            ['province_id' => $provinces['19'], 'name' => 'Kabupaten Bangka Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['19'], 'name' => 'Kabupaten Bangka Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['19'], 'name' => 'Kabupaten Bangka Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['19'], 'name' => 'Kabupaten Belitung', 'type' => 'kabupaten'],
            ['province_id' => $provinces['19'], 'name' => 'Kabupaten Belitung Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['19'], 'name' => 'Kota Pangkal Pinang', 'type' => 'kota'],

            // Kepulauan Riau (21)
            ['province_id' => $provinces['21'], 'name' => 'Kabupaten Bintan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['21'], 'name' => 'Kabupaten Karimun', 'type' => 'kabupaten'],
            ['province_id' => $provinces['21'], 'name' => 'Kabupaten Kepulauan Anambas', 'type' => 'kabupaten'],
            ['province_id' => $provinces['21'], 'name' => 'Kabupaten Lingga', 'type' => 'kabupaten'],
            ['province_id' => $provinces['21'], 'name' => 'Kabupaten Natuna', 'type' => 'kabupaten'],
            ['province_id' => $provinces['21'], 'name' => 'Kota Batam', 'type' => 'kota'],
            ['province_id' => $provinces['21'], 'name' => 'Kota Tanjung Pinang', 'type' => 'kota'],

            // DKI Jakarta (31)
            ['province_id' => $provinces['31'], 'name' => 'Kabupaten Kepulauan Seribu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['31'], 'name' => 'Kota Jakarta Barat', 'type' => 'kota'],
            ['province_id' => $provinces['31'], 'name' => 'Kota Jakarta Pusat', 'type' => 'kota'],
            ['province_id' => $provinces['31'], 'name' => 'Kota Jakarta Selatan', 'type' => 'kota'],
            ['province_id' => $provinces['31'], 'name' => 'Kota Jakarta Timur', 'type' => 'kota'],
            ['province_id' => $provinces['31'], 'name' => 'Kota Jakarta Utara', 'type' => 'kota'],

            // Jawa Barat (32)
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Bandung', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Bandung Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Bekasi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Bogor', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Ciamis', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Cianjur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Cirebon', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Garut', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Indramayu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Karawang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Kuningan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Majalengka', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Pangandaran', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Purwakarta', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Subang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Sukabumi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Sumedang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kabupaten Tasikmalaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Bandung', 'type' => 'kota'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Banjar', 'type' => 'kota'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Bekasi', 'type' => 'kota'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Bogor', 'type' => 'kota'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Cimahi', 'type' => 'kota'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Cirebon', 'type' => 'kota'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Depok', 'type' => 'kota'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Sukabumi', 'type' => 'kota'],
            ['province_id' => $provinces['32'], 'name' => 'Kota Tasikmalaya', 'type' => 'kota'],

            // Jawa Tengah (33)
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Banjarnegara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Banyumas', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Batang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Blora', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Boyolali', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Brebes', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Cilacap', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Demak', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Grobogan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Jepara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Karanganyar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Kebumen', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Kendal', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Klaten', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Kudus', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Magelang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Pati', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Pekalongan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Pemalang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Purbalingga', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Purworejo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Rembang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Semarang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Sragen', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Sukoharjo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Tegal', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Temanggung', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Wonogiri', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kabupaten Wonosobo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['33'], 'name' => 'Kota Magelang', 'type' => 'kota'],
            ['province_id' => $provinces['33'], 'name' => 'Kota Pekalongan', 'type' => 'kota'],
            ['province_id' => $provinces['33'], 'name' => 'Kota Salatiga', 'type' => 'kota'],
            ['province_id' => $provinces['33'], 'name' => 'Kota Semarang', 'type' => 'kota'],
            ['province_id' => $provinces['33'], 'name' => 'Kota Surakarta', 'type' => 'kota'],
            ['province_id' => $provinces['33'], 'name' => 'Kota Tegal', 'type' => 'kota'],

            // DI Yogyakarta (34)
            ['province_id' => $provinces['34'], 'name' => 'Kabupaten Bantul', 'type' => 'kabupaten'],
            ['province_id' => $provinces['34'], 'name' => 'Kabupaten Gunungkidul', 'type' => 'kabupaten'],
            ['province_id' => $provinces['34'], 'name' => 'Kabupaten Kulon Progo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['34'], 'name' => 'Kabupaten Sleman', 'type' => 'kabupaten'],
            ['province_id' => $provinces['34'], 'name' => 'Kota Yogyakarta', 'type' => 'kota'],

            // Jawa Timur (35)
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Bangkalan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Banyuwangi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Blitar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Bojonegoro', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Bondowoso', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Gresik', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Jember', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Jombang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Kediri', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Lamongan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Lumajang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Madiun', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Magetan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Malang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Mojokerto', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Nganjuk', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Ngawi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Pacitan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Pamekasan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Pasuruan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Ponorogo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Probolinggo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Sampang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Sidoarjo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Situbondo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Sumenep', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Trenggalek', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Tuban', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kabupaten Tulungagung', 'type' => 'kabupaten'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Batu', 'type' => 'kota'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Blitar', 'type' => 'kota'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Kediri', 'type' => 'kota'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Madiun', 'type' => 'kota'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Malang', 'type' => 'kota'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Mojokerto', 'type' => 'kota'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Pasuruan', 'type' => 'kota'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Probolinggo', 'type' => 'kota'],
            ['province_id' => $provinces['35'], 'name' => 'Kota Surabaya', 'type' => 'kota'],

            // Banten (36)
            ['province_id' => $provinces['36'], 'name' => 'Kabupaten Lebak', 'type' => 'kabupaten'],
            ['province_id' => $provinces['36'], 'name' => 'Kabupaten Pandeglang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['36'], 'name' => 'Kabupaten Serang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['36'], 'name' => 'Kabupaten Tangerang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['36'], 'name' => 'Kota Cilegon', 'type' => 'kota'],
            ['province_id' => $provinces['36'], 'name' => 'Kota Serang', 'type' => 'kota'],
            ['province_id' => $provinces['36'], 'name' => 'Kota Tangerang', 'type' => 'kota'],
            ['province_id' => $provinces['36'], 'name' => 'Kota Tangerang Selatan', 'type' => 'kota'],

            // Bali (51)
            ['province_id' => $provinces['51'], 'name' => 'Kabupaten Badung', 'type' => 'kabupaten'],
            ['province_id' => $provinces['51'], 'name' => 'Kabupaten Bangli', 'type' => 'kabupaten'],
            ['province_id' => $provinces['51'], 'name' => 'Kabupaten Buleleng', 'type' => 'kabupaten'],
            ['province_id' => $provinces['51'], 'name' => 'Kabupaten Gianyar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['51'], 'name' => 'Kabupaten Jembrana', 'type' => 'kabupaten'],
            ['province_id' => $provinces['51'], 'name' => 'Kabupaten Karangasem', 'type' => 'kabupaten'],
            ['province_id' => $provinces['51'], 'name' => 'Kabupaten Klungkung', 'type' => 'kabupaten'],
            ['province_id' => $provinces['51'], 'name' => 'Kabupaten Tabanan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['51'], 'name' => 'Kota Denpasar', 'type' => 'kota'],

            // Nusa Tenggara Barat (52)
            ['province_id' => $provinces['52'], 'name' => 'Kabupaten Bima', 'type' => 'kabupaten'],
            ['province_id' => $provinces['52'], 'name' => 'Kabupaten Dompu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['52'], 'name' => 'Kabupaten Lombok Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['52'], 'name' => 'Kabupaten Lombok Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['52'], 'name' => 'Kabupaten Lombok Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['52'], 'name' => 'Kabupaten Lombok Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['52'], 'name' => 'Kabupaten Sumbawa', 'type' => 'kabupaten'],
            ['province_id' => $provinces['52'], 'name' => 'Kabupaten Sumbawa Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['52'], 'name' => 'Kota Bima', 'type' => 'kota'],
            ['province_id' => $provinces['52'], 'name' => 'Kota Mataram', 'type' => 'kota'],

            // Nusa Tenggara Timur (53)
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Alor', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Belu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Ende', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Flores Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Kupang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Lembata', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Malaka', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Manggarai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Manggarai Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Manggarai Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Nagekeo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Ngada', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Rote Ndao', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Sabu Raijua', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Sikka', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Sumba Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Sumba Barat Daya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Sumba Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Sumba Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Timor Tengah Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kabupaten Timor Tengah Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['53'], 'name' => 'Kota Kupang', 'type' => 'kota'],

            // Kalimantan Barat (61)
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Bengkayang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Kapuas Hulu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Kayong Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Ketapang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Kubu Raya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Landak', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Melawi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Mempawah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Sambas', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Sanggau', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Sekadau', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kabupaten Sintang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['61'], 'name' => 'Kota Pontianak', 'type' => 'kota'],
            ['province_id' => $provinces['61'], 'name' => 'Kota Singkawang', 'type' => 'kota'],

            // Kalimantan Tengah (62)
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Barito Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Barito Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Barito Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Gunung Mas', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Kapuas', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Katingan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Kotawaringin Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Kotawaringin Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Lamandau', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Murung Raya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Pulang Pisau', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Seruyan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kabupaten Sukamara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['62'], 'name' => 'Kota Palangka Raya', 'type' => 'kota'],

            // Kalimantan Selatan (63)
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Balangan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Banjar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Barito Kuala', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Hulu Sungai Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Hulu Sungai Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Hulu Sungai Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Kotabaru', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Tabalong', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Tanah Bumbu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Tanah Laut', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kabupaten Tapin', 'type' => 'kabupaten'],
            ['province_id' => $provinces['63'], 'name' => 'Kota Banjarbaru', 'type' => 'kota'],
            ['province_id' => $provinces['63'], 'name' => 'Kota Banjarmasin', 'type' => 'kota'],

            // Kalimantan Timur (64)
            ['province_id' => $provinces['64'], 'name' => 'Kabupaten Berau', 'type' => 'kabupaten'],
            ['province_id' => $provinces['64'], 'name' => 'Kabupaten Kutai Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['64'], 'name' => 'Kabupaten Kutai Kartanegara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['64'], 'name' => 'Kabupaten Kutai Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['64'], 'name' => 'Kabupaten Mahakam Ulu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['64'], 'name' => 'Kabupaten Paser', 'type' => 'kabupaten'],
            ['province_id' => $provinces['64'], 'name' => 'Kabupaten Penajam Paser Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['64'], 'name' => 'Kota Balikpapan', 'type' => 'kota'],
            ['province_id' => $provinces['64'], 'name' => 'Kota Bontang', 'type' => 'kota'],
            ['province_id' => $provinces['64'], 'name' => 'Kota Samarinda', 'type' => 'kota'],

            // Kalimantan Utara (65)
            ['province_id' => $provinces['65'], 'name' => 'Kabupaten Bulungan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['65'], 'name' => 'Kabupaten Malinau', 'type' => 'kabupaten'],
            ['province_id' => $provinces['65'], 'name' => 'Kabupaten Nunukan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['65'], 'name' => 'Kabupaten Tana Tidung', 'type' => 'kabupaten'],
            ['province_id' => $provinces['65'], 'name' => 'Kota Tarakan', 'type' => 'kota'],

            // Sulawesi Utara (71)
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Bolaang Mongondow', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Bolaang Mongondow Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Bolaang Mongondow Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Bolaang Mongondow Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Kepulauan Sangihe', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Kepulauan Siau Tagulandang Biaro', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Kepulauan Talaud', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Minahasa', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Minahasa Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Minahasa Tenggara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kabupaten Minahasa Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['71'], 'name' => 'Kota Bitung', 'type' => 'kota'],
            ['province_id' => $provinces['71'], 'name' => 'Kota Kotamobagu', 'type' => 'kota'],
            ['province_id' => $provinces['71'], 'name' => 'Kota Manado', 'type' => 'kota'],
            ['province_id' => $provinces['71'], 'name' => 'Kota Tomohon', 'type' => 'kota'],

            // Sulawesi Tengah (72)
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Banggai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Banggai Kepulauan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Banggai Laut', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Buol', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Donggala', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Morowali', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Morowali Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Parigi Moutong', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Poso', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Sigi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Tojo Una-Una', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kabupaten Tolitoli', 'type' => 'kabupaten'],
            ['province_id' => $provinces['72'], 'name' => 'Kota Palu', 'type' => 'kota'],

            // Sulawesi Selatan (73)
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Bantaeng', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Barru', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Bone', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Bulukumba', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Enrekang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Gowa', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Jeneponto', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Kepulauan Selayar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Luwu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Luwu Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Luwu Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Maros', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Pangkajene dan Kepulauan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Pinrang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Sidenreng Rappang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Sinjai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Soppeng', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Takalar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Tana Toraja', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Toraja Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kabupaten Wajo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['73'], 'name' => 'Kota Makassar', 'type' => 'kota'],
            ['province_id' => $provinces['73'], 'name' => 'Kota Palopo', 'type' => 'kota'],
            ['province_id' => $provinces['73'], 'name' => 'Kota Parepare', 'type' => 'kota'],

            // Sulawesi Tenggara (74)
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Bombana', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Buton', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Buton Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Buton Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Buton Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Kolaka', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Kolaka Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Kolaka Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Konawe', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Konawe Kepulauan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Konawe Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Konawe Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Muna', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Muna Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kabupaten Wakatobi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['74'], 'name' => 'Kota Baubau', 'type' => 'kota'],
            ['province_id' => $provinces['74'], 'name' => 'Kota Kendari', 'type' => 'kota'],

            // Gorontalo (75)
            ['province_id' => $provinces['75'], 'name' => 'Kabupaten Boalemo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['75'], 'name' => 'Kabupaten Bone Bolango', 'type' => 'kabupaten'],
            ['province_id' => $provinces['75'], 'name' => 'Kabupaten Gorontalo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['75'], 'name' => 'Kabupaten Gorontalo Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['75'], 'name' => 'Kabupaten Pohuwato', 'type' => 'kabupaten'],
            ['province_id' => $provinces['75'], 'name' => 'Kota Gorontalo', 'type' => 'kota'],

            // Sulawesi Barat (76)
            ['province_id' => $provinces['76'], 'name' => 'Kabupaten Majene', 'type' => 'kabupaten'],
            ['province_id' => $provinces['76'], 'name' => 'Kabupaten Mamasa', 'type' => 'kabupaten'],
            ['province_id' => $provinces['76'], 'name' => 'Kabupaten Mamuju', 'type' => 'kabupaten'],
            ['province_id' => $provinces['76'], 'name' => 'Kabupaten Mamuju Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['76'], 'name' => 'Kabupaten Mamuju Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['76'], 'name' => 'Kabupaten Polewali Mandar', 'type' => 'kabupaten'],

            // Maluku (81)
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Buru', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Buru Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Kepulauan Aru', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Kepulauan Tanimbar', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Maluku Barat Daya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Maluku Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Maluku Tenggara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Seram Bagian Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kabupaten Seram Bagian Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['81'], 'name' => 'Kota Ambon', 'type' => 'kota'],
            ['province_id' => $provinces['81'], 'name' => 'Kota Tual', 'type' => 'kota'],

            // Maluku Utara (82)
            ['province_id' => $provinces['82'], 'name' => 'Kabupaten Halmahera Barat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['82'], 'name' => 'Kabupaten Halmahera Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['82'], 'name' => 'Kabupaten Halmahera Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['82'], 'name' => 'Kabupaten Halmahera Timur', 'type' => 'kabupaten'],
            ['province_id' => $provinces['82'], 'name' => 'Kabupaten Halmahera Utara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['82'], 'name' => 'Kabupaten Kepulauan Sula', 'type' => 'kabupaten'],
            ['province_id' => $provinces['82'], 'name' => 'Kabupaten Pulau Morotai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['82'], 'name' => 'Kabupaten Pulau Taliabu', 'type' => 'kabupaten'],
            ['province_id' => $provinces['82'], 'name' => 'Kota Ternate', 'type' => 'kota'],
            ['province_id' => $provinces['82'], 'name' => 'Kota Tidore Kepulauan', 'type' => 'kota'],

            // Papua Barat (91)
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Fakfak', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Kaimana', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Manokwari', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Manokwari Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Maybrat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Pegunungan Arfak', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Raja Ampat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Sorong', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Sorong Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Tambrauw', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Teluk Bintuni', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kabupaten Teluk Wondama', 'type' => 'kabupaten'],
            ['province_id' => $provinces['91'], 'name' => 'Kota Sorong', 'type' => 'kota'],

            // Papua (92)
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Asmat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Biak Numfor', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Boven Digoel', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Deiyai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Dogiyai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Intan Jaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Jayapura', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Jayawijaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Keerom', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Kepulauan Yapen', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Lanny Jaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Mamberamo Raya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Mamberamo Tengah', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Mappi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Merauke', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Mimika', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Nabire', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Nduga', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Paniai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Pegunungan Bintang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Puncak', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Puncak Jaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Sarmi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Supiori', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Tolikara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Waropen', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Yahukimo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kabupaten Yalimo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['92'], 'name' => 'Kota Jayapura', 'type' => 'kota'],

            // Papua Selatan (93)
            ['province_id' => $provinces['93'], 'name' => 'Kabupaten Merauke', 'type' => 'kabupaten'],
            ['province_id' => $provinces['93'], 'name' => 'Kabupaten Mappi', 'type' => 'kabupaten'],
            ['province_id' => $provinces['93'], 'name' => 'Kabupaten Asmat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['93'], 'name' => 'Kabupaten Boven Digoel', 'type' => 'kabupaten'],

            // Papua Tengah (94)
            ['province_id' => $provinces['94'], 'name' => 'Kabupaten Nabire', 'type' => 'kabupaten'],
            ['province_id' => $provinces['94'], 'name' => 'Kabupaten Paniai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['94'], 'name' => 'Kabupaten Dogiyai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['94'], 'name' => 'Kabupaten Deiyai', 'type' => 'kabupaten'],
            ['province_id' => $provinces['94'], 'name' => 'Kabupaten Intan Jaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['94'], 'name' => 'Kabupaten Mimika', 'type' => 'kabupaten'],
            ['province_id' => $provinces['94'], 'name' => 'Kabupaten Puncak Jaya', 'type' => 'kabupaten'],

            // Papua Pegunungan (95)
            ['province_id' => $provinces['95'], 'name' => 'Kabupaten Jayawijaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['95'], 'name' => 'Kabupaten Lanny Jaya', 'type' => 'kabupaten'],
            ['province_id' => $provinces['95'], 'name' => 'Kabupaten Nduga', 'type' => 'kabupaten'],
            ['province_id' => $provinces['95'], 'name' => 'Kabupaten Pegunungan Bintang', 'type' => 'kabupaten'],
            ['province_id' => $provinces['95'], 'name' => 'Kabupaten Tolikara', 'type' => 'kabupaten'],
            ['province_id' => $provinces['95'], 'name' => 'Kabupaten Yahukimo', 'type' => 'kabupaten'],
            ['province_id' => $provinces['95'], 'name' => 'Kabupaten Yalimo', 'type' => 'kabupaten'],

            // Papua Barat Daya (96)
            ['province_id' => $provinces['96'], 'name' => 'Kabupaten Sorong Selatan', 'type' => 'kabupaten'],
            ['province_id' => $provinces['96'], 'name' => 'Kabupaten Maybrat', 'type' => 'kabupaten'],
            ['province_id' => $provinces['96'], 'name' => 'Kabupaten Tambrauw', 'type' => 'kabupaten'],
            ['province_id' => $provinces['96'], 'name' => 'Kabupaten Raja Ampat', 'type' => 'kabupaten'],
        ];

        // Insert data dengan chunk untuk menghindari memory limit
        foreach (array_chunk($cities, 100) as $chunk) {
            DB::table('city')->insert($chunk);
        }
    }
}