<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            // Aceh (11)
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Barat', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Barat Daya', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Besar', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Jaya', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Selatan', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Singkil', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Tamiang', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Tengah', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Tenggara', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Timur', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Aceh Utara', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Bener Meriah', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Bireuen', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Gayo Lues', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Nagan Raya', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Pidie', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Pidie Jaya', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kabupaten Simeulue', 'type' => 'kabupaten'],
            ['province_id' => 1, 'name' => 'Kota Banda Aceh', 'type' => 'kota'],
            ['province_id' => 1, 'name' => 'Kota Langsa', 'type' => 'kota'],
            ['province_id' => 1, 'name' => 'Kota Lhokseumawe', 'type' => 'kota'],
            ['province_id' => 1, 'name' => 'Kota Sabang', 'type' => 'kota'],
            ['province_id' => 1, 'name' => 'Kota Subulussalam', 'type' => 'kota'],

            // Sumatera Utara (12)
            ['province_id' => 2, 'name' => 'Kabupaten Asahan', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Batubara', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Dairi', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Deli Serdang', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Humbang Hasundutan', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Karo', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Labuhanbatu', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Labuhanbatu Selatan', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Labuhanbatu Utara', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Langkat', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Mandailing Natal', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Nias', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Nias Barat', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Nias Selatan', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Nias Utara', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Padang Lawas', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Padang Lawas Utara', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Pakpak Bharat', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Samosir', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Serdang Bedagai', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Simalungun', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Tapanuli Selatan', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Tapanuli Tengah', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Tapanuli Utara', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kabupaten Toba Samosir', 'type' => 'kabupaten'],
            ['province_id' => 2, 'name' => 'Kota Binjai', 'type' => 'kota'],
            ['province_id' => 2, 'name' => 'Kota Gunungsitoli', 'type' => 'kota'],
            ['province_id' => 2, 'name' => 'Kota Medan', 'type' => 'kota'],
            ['province_id' => 2, 'name' => 'Kota Padangsidempuan', 'type' => 'kota'],
            ['province_id' => 2, 'name' => 'Kota Pematangsiantar', 'type' => 'kota'],
            ['province_id' => 2, 'name' => 'Kota Sibolga', 'type' => 'kota'],
            ['province_id' => 2, 'name' => 'Kota Tanjungbalai', 'type' => 'kota'],
            ['province_id' => 2, 'name' => 'Kota Tebing Tinggi', 'type' => 'kota'],

            // Sumatera Barat (13)
            ['province_id' => 3, 'name' => 'Kabupaten Agam', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Dharmasraya', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Kepulauan Mentawai', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Lima Puluh Kota', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Padang Pariaman', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Pasaman', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Pasaman Barat', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Pesisir Selatan', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Sijunjung', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Solok', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Solok Selatan', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kabupaten Tanah Datar', 'type' => 'kabupaten'],
            ['province_id' => 3, 'name' => 'Kota Bukittinggi', 'type' => 'kota'],
            ['province_id' => 3, 'name' => 'Kota Padang', 'type' => 'kota'],
            ['province_id' => 3, 'name' => 'Kota Padangpanjang', 'type' => 'kota'],
            ['province_id' => 3, 'name' => 'Kota Pariaman', 'type' => 'kota'],
            ['province_id' => 3, 'name' => 'Kota Payakumbuh', 'type' => 'kota'],
            ['province_id' => 3, 'name' => 'Kota Sawahlunto', 'type' => 'kota'],
            ['province_id' => 3, 'name' => 'Kota Solok', 'type' => 'kota'],

            // Riau (14)
            ['province_id' => 4, 'name' => 'Kabupaten Bengkalis', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Indragiri Hilir', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Indragiri Hulu', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Kampar', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Kepulauan Meranti', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Kuantan Singingi', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Pelalawan', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Rokan Hilir', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Rokan Hulu', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kabupaten Siak', 'type' => 'kabupaten'],
            ['province_id' => 4, 'name' => 'Kota Dumai', 'type' => 'kota'],
            ['province_id' => 4, 'name' => 'Kota Pekanbaru', 'type' => 'kota'],

            // Jambi (15)
            ['province_id' => 5, 'name' => 'Kabupaten Batanghari', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kabupaten Bungo', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kabupaten Kerinci', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kabupaten Merangin', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kabupaten Muaro Jambi', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kabupaten Sarolangun', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kabupaten Tanjung Jabung Barat', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kabupaten Tanjung Jabung Timur', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kabupaten Tebo', 'type' => 'kabupaten'],
            ['province_id' => 5, 'name' => 'Kota Jambi', 'type' => 'kota'],
            ['province_id' => 5, 'name' => 'Kota Sungai Penuh', 'type' => 'kota'],

            // Sumatera Selatan (16)
            ['province_id' => 6, 'name' => 'Kabupaten Banyuasin', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Empat Lawang', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Lahat', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Muara Enim', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Musi Banyuasin', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Musi Rawas', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Musi Rawas Utara', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Ogan Ilir', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Ogan Komering Ilir', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Ogan Komering Ulu', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Ogan Komering Ulu Selatan', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Ogan Komering Ulu Timur', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kabupaten Penukal Abab Lematang Ilir', 'type' => 'kabupaten'],
            ['province_id' => 6, 'name' => 'Kota Lubuklinggau', 'type' => 'kota'],
            ['province_id' => 6, 'name' => 'Kota Pagar Alam', 'type' => 'kota'],
            ['province_id' => 6, 'name' => 'Kota Palembang', 'type' => 'kota'],
            ['province_id' => 6, 'name' => 'Kota Prabumulih', 'type' => 'kota'],

            // Bengkulu (17)
            ['province_id' => 7, 'name' => 'Kabupaten Bengkulu Selatan', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kabupaten Bengkulu Tengah', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kabupaten Bengkulu Utara', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kabupaten Kaur', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kabupaten Kepahiang', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kabupaten Lebong', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kabupaten Mukomuko', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kabupaten Rejang Lebong', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kabupaten Seluma', 'type' => 'kabupaten'],
            ['province_id' => 7, 'name' => 'Kota Bengkulu', 'type' => 'kota'],

            // Lampung (18)
            ['province_id' => 8, 'name' => 'Kabupaten Lampung Barat', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Lampung Selatan', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Lampung Tengah', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Lampung Timur', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Lampung Utara', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Mesuji', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Pesawaran', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Pesisir Barat', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Pringsewu', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Tanggamus', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Tulang Bawang', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Tulang Bawang Barat', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kabupaten Way Kanan', 'type' => 'kabupaten'],
            ['province_id' => 8, 'name' => 'Kota Bandar Lampung', 'type' => 'kota'],
            ['province_id' => 8, 'name' => 'Kota Metro', 'type' => 'kota'],

            // Kepulauan Bangka Belitung (19)
            ['province_id' => 9, 'name' => 'Kabupaten Bangka', 'type' => 'kabupaten'],
            ['province_id' => 9, 'name' => 'Kabupaten Bangka Barat', 'type' => 'kabupaten'],
            ['province_id' => 9, 'name' => 'Kabupaten Bangka Selatan', 'type' => 'kabupaten'],
            ['province_id' => 9, 'name' => 'Kabupaten Bangka Tengah', 'type' => 'kabupaten'],
            ['province_id' => 9, 'name' => 'Kabupaten Belitung', 'type' => 'kabupaten'],
            ['province_id' => 9, 'name' => 'Kabupaten Belitung Timur', 'type' => 'kabupaten'],
            ['province_id' => 9, 'name' => 'Kota Pangkal Pinang', 'type' => 'kota'],

            // Kepulauan Riau (21)
            ['province_id' => 10, 'name' => 'Kabupaten Bintan', 'type' => 'kabupaten'],
            ['province_id' => 10, 'name' => 'Kabupaten Karimun', 'type' => 'kabupaten'],
            ['province_id' => 10, 'name' => 'Kabupaten Kepulauan Anambas', 'type' => 'kabupaten'],
            ['province_id' => 10, 'name' => 'Kabupaten Lingga', 'type' => 'kabupaten'],
            ['province_id' => 10, 'name' => 'Kabupaten Natuna', 'type' => 'kabupaten'],
            ['province_id' => 10, 'name' => 'Kota Batam', 'type' => 'kota'],
            ['province_id' => 10, 'name' => 'Kota Tanjung Pinang', 'type' => 'kota'],

            // DKI Jakarta (31)
            ['province_id' => 11, 'name' => 'Kabupaten Kepulauan Seribu', 'type' => 'kabupaten'],
            ['province_id' => 11, 'name' => 'Kota Jakarta Barat', 'type' => 'kota'],
            ['province_id' => 11, 'name' => 'Kota Jakarta Pusat', 'type' => 'kota'],
            ['province_id' => 11, 'name' => 'Kota Jakarta Selatan', 'type' => 'kota'],
            ['province_id' => 11, 'name' => 'Kota Jakarta Timur', 'type' => 'kota'],
            ['province_id' => 11, 'name' => 'Kota Jakarta Utara', 'type' => 'kota'],

            // Jawa Barat (32)
            ['province_id' => 12, 'name' => 'Kabupaten Bandung', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Bandung Barat', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Bekasi', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Bogor', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Ciamis', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Cianjur', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Cirebon', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Garut', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Indramayu', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Karawang', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Kuningan', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Majalengka', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Pangandaran', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Purwakarta', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Subang', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Sukabumi', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Sumedang', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kabupaten Tasikmalaya', 'type' => 'kabupaten'],
            ['province_id' => 12, 'name' => 'Kota Bandung', 'type' => 'kota'],
            ['province_id' => 12, 'name' => 'Kota Banjar', 'type' => 'kota'],
            ['province_id' => 12, 'name' => 'Kota Bekasi', 'type' => 'kota'],
            ['province_id' => 12, 'name' => 'Kota Bogor', 'type' => 'kota'],
            ['province_id' => 12, 'name' => 'Kota Cimahi', 'type' => 'kota'],
            ['province_id' => 12, 'name' => 'Kota Cirebon', 'type' => 'kota'],
            ['province_id' => 12, 'name' => 'Kota Depok', 'type' => 'kota'],
            ['province_id' => 12, 'name' => 'Kota Sukabumi', 'type' => 'kota'],
            ['province_id' => 12, 'name' => 'Kota Tasikmalaya', 'type' => 'kota'],

            // Jawa Tengah (33)
            ['province_id' => 13, 'name' => 'Kabupaten Banjarnegara', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Banyumas', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Batang', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Blora', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Boyolali', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Brebes', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Cilacap', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Demak', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Grobogan', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Jepara', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Karanganyar', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Kebumen', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Kendal', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Klaten', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Kudus', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Magelang', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Pati', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Pekalongan', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Pemalang', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Purbalingga', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Purworejo', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Rembang', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Semarang', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Sragen', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Sukoharjo', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Tegal', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Temanggung', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Wonogiri', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kabupaten Wonosobo', 'type' => 'kabupaten'],
            ['province_id' => 13, 'name' => 'Kota Magelang', 'type' => 'kota'],
            ['province_id' => 13, 'name' => 'Kota Pekalongan', 'type' => 'kota'],
            ['province_id' => 13, 'name' => 'Kota Salatiga', 'type' => 'kota'],
            ['province_id' => 13, 'name' => 'Kota Semarang', 'type' => 'kota'],
            ['province_id' => 13, 'name' => 'Kota Surakarta', 'type' => 'kota'],
            ['province_id' => 13, 'name' => 'Kota Tegal', 'type' => 'kota'],

            // DI Yogyakarta (34)
            ['province_id' => 14, 'name' => 'Kabupaten Bantul', 'type' => 'kabupaten'],
            ['province_id' => 14, 'name' => 'Kabupaten Gunungkidul', 'type' => 'kabupaten'],
            ['province_id' => 14, 'name' => 'Kabupaten Kulon Progo', 'type' => 'kabupaten'],
            ['province_id' => 14, 'name' => 'Kabupaten Sleman', 'type' => 'kabupaten'],
            ['province_id' => 14, 'name' => 'Kota Yogyakarta', 'type' => 'kota'],

            // Jawa Timur (35)
            ['province_id' => 15, 'name' => 'Kabupaten Bangkalan', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Banyuwangi', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Blitar', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Bojonegoro', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Bondowoso', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Gresik', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Jember', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Jombang', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Kediri', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Lamongan', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Lumajang', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Madiun', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Magetan', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Malang', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Mojokerto', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Nganjuk', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Ngawi', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Pacitan', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Pamekasan', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Pasuruan', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Ponorogo', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Probolinggo', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Sampang', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Sidoarjo', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Situbondo', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Sumenep', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Trenggalek', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Tuban', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kabupaten Tulungagung', 'type' => 'kabupaten'],
            ['province_id' => 15, 'name' => 'Kota Batu', 'type' => 'kota'],
            ['province_id' => 15, 'name' => 'Kota Blitar', 'type' => 'kota'],
            ['province_id' => 15, 'name' => 'Kota Kediri', 'type' => 'kota'],
            ['province_id' => 15, 'name' => 'Kota Madiun', 'type' => 'kota'],
            ['province_id' => 15, 'name' => 'Kota Malang', 'type' => 'kota'],
            ['province_id' => 15, 'name' => 'Kota Mojokerto', 'type' => 'kota'],
            ['province_id' => 15, 'name' => 'Kota Pasuruan', 'type' => 'kota'],
            ['province_id' => 15, 'name' => 'Kota Probolinggo', 'type' => 'kota'],
            ['province_id' => 15, 'name' => 'Kota Surabaya', 'type' => 'kota'],

            // Banten (36)
            ['province_id' => 16, 'name' => 'Kabupaten Lebak', 'type' => 'kabupaten'],
            ['province_id' => 16, 'name' => 'Kabupaten Pandeglang', 'type' => 'kabupaten'],
            ['province_id' => 16, 'name' => 'Kabupaten Serang', 'type' => 'kabupaten'],
            ['province_id' => 16, 'name' => 'Kabupaten Tangerang', 'type' => 'kabupaten'],
            ['province_id' => 16, 'name' => 'Kota Cilegon', 'type' => 'kota'],
            ['province_id' => 16, 'name' => 'Kota Serang', 'type' => 'kota'],
            ['province_id' => 16, 'name' => 'Kota Tangerang', 'type' => 'kota'],
            ['province_id' => 16, 'name' => 'Kota Tangerang Selatan', 'type' => 'kota'],

            // Bali (51)
            ['province_id' => 17, 'name' => 'Kabupaten Badung', 'type' => 'kabupaten'],
            ['province_id' => 17, 'name' => 'Kabupaten Bangli', 'type' => 'kabupaten'],
            ['province_id' => 17, 'name' => 'Kabupaten Buleleng', 'type' => 'kabupaten'],
            ['province_id' => 17, 'name' => 'Kabupaten Gianyar', 'type' => 'kabupaten'],
            ['province_id' => 17, 'name' => 'Kabupaten Jembrana', 'type' => 'kabupaten'],
            ['province_id' => 17, 'name' => 'Kabupaten Karangasem', 'type' => 'kabupaten'],
            ['province_id' => 17, 'name' => 'Kabupaten Klungkung', 'type' => 'kabupaten'],
            ['province_id' => 17, 'name' => 'Kabupaten Tabanan', 'type' => 'kabupaten'],
            ['province_id' => 17, 'name' => 'Kota Denpasar', 'type' => 'kota'],
        ];

        DB::table('cities')->insert($cities);
    }
}
