<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiseasesSeeder extends Seeder
{
    public function run(): void
    {
        $diseases = [
        
            [
                'name' => 'Foot and Mouth Disease (FMD)',
                'disease_code' => 'FMD-001',
                'causative_agent' => 'Virus Aphthovirus',
                'description' => 'Penyakit mulut dan kuku adalah penyakit menular yang sangat menular yang mempengaruhi ruminansia dan babi. Ditandai dengan demam tinggi dan lepuh pada mulut dan kuku.',
                'transmission_method' => 'Melalui kontak langsung dengan hewan yang terinfeksi, air, pakan, atau objek yang terkontaminasi.',
                'general_treatment' => 'Tidak ada pengobatan spesifik. Vaksinasi preventif dan isolasi hewan yang terinfeksi. Perawatan suportif untuk mencegah infeksi sekunder.',
                'prevention_method' => 'Vaksinasi rutin, biosekuriti ketat, karantina hewan baru, desinfeksi kandang dan peralatan.',
                'risk_factors' => 'Kepadatan ternak tinggi, transportasi hewan, kontaminasi pakan dan air.',
                'is_zoonotic' => 1,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 0,
                'is_viral' => 1,
                'image' => 'diseases/fmd.jpg',
            ],
            [
                'name' => 'Avian Influenza (Flu Burung)',
                'disease_code' => 'AI-002',
                'causative_agent' => 'Virus Influenza A',
                'description' => 'Penyakit pernapasan akut pada unggas yang disebabkan oleh virus influenza. Dapat menyebabkan kematian tinggi dalam waktu singkat.',
                'transmission_method' => 'Melalui kontak dengan unggas yang terinfeksi, feses, atau lingkungan yang terkontaminasi. Juga melalui udara.',
                'general_treatment' => 'Tidak ada pengobatan spesifik. Vaksinasi dan biosecurity. Isolasi dan depopulasi pada kasus berat.',
                'prevention_method' => 'Vaksinasi, biosekuriti ketat, monitoring rutin, kontrol lalu lintas unggas.',
                'risk_factors' => 'Peternakan dengan multi-usia, kontak dengan unggas liar, sanitasi buruk.',
                'is_zoonotic' => 1,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 0,
                'is_viral' => 1,
                'image' => 'diseases/avian-influenza.jpg',
            ],
            [
                'name' => 'Brucellosis',
                'disease_code' => 'BRU-003',
                'causative_agent' => 'Bakteri Brucella spp',
                'description' => 'Penyakit bakteri yang mempengaruhi reproduksi hewan dan dapat menular ke manusia. Menyebabkan abortus dan infertilitas.',
                'transmission_method' => 'Melalui kontak dengan cairan reproduksi, susu, atau jaringan hewan yang terinfeksi.',
                'general_treatment' => 'Antibiotik untuk manusia; vaksinasi untuk hewan. Pengobatan jangka panjang diperlukan.',
                'prevention_method' => 'Vaksinasi, testing rutin, isolasi hewan positif, pasteurisasi susu.',
                'risk_factors' => 'Kawin alam, persalinan tanpa isolasi, konsumsi produk susu mentah.',
                'is_zoonotic' => 1,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 1,
                'is_viral' => 0,
                'image' => 'diseases/brucellosis.jpg',
            ],
            [
                'name' => 'Newcastle Disease',
                'disease_code' => 'ND-004',
                'causative_agent' => 'Virus Avian Paramyxovirus',
                'description' => 'Penyakit pernapasan dan saraf pada unggas yang sangat menular. Dapat menyebabkan kematian hingga 100% pada ternak rentan.',
                'transmission_method' => 'Melalui kontak langsung, udara, atau objek yang terkontaminasi. Juga melalui pakan dan air.',
                'general_treatment' => 'Vaksinasi preventif. Tidak ada pengobatan spesifik untuk kasus klinis.',
                'prevention_method' => 'Vaksinasi rutin, biosekuriti, kontrol lalu lintas unggas, sanitasi kandang.',
                'risk_factors' => 'Kepadatan tinggi, ventilasi buruk, multi-usia dalam satu kandang.',
                'is_zoonotic' => 0,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 0,
                'is_viral' => 1,
                'image' => 'diseases/newcastle.jpg',
            ],
            [
                'name' => 'Mastitis',
                'disease_code' => 'MAS-005',
                'causative_agent' => 'Bakteri Staphylococcus, Streptococcus',
                'description' => 'Peradangan pada ambing sapi yang menyebabkan penurunan produksi susu dan kualitas susu. Dapat bersifat klinis atau subklinis.',
                'transmission_method' => 'Melalui luka pada putting atau kondisi sanitasi yang buruk selama pemerahan.',
                'general_treatment' => 'Antibiotik intramammary, perawatan suportif, kompres hangat, anti-inflamasi.',
                'prevention_method' => 'Kebersihan pemerahan, dipping putting, perawatan putting, manajemen kandang bersih.',
                'risk_factors' => 'Mesin perah tidak steril, kebersihan pekerja, luka pada putting, kandang basah.',
                'is_zoonotic' => 0,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 1,
                'is_viral' => 0,
                'image' => 'diseases/mastitis.jpg',
            ],
            [
                'name' => 'Anthrax (Penyakit Sapi Gila)',
                'disease_code' => 'ANT-006',
                'causative_agent' => 'Bakteri Bacillus anthracis',
                'description' => 'Penyakit bakterial akut dan mematikan yang dapat mempengaruhi hampir semua hewan berdarah panas. Ditandai dengan pendarahan tiba-tiba dan pembengkakan.',
                'transmission_method' => 'Melalui spora di tanah, pakan, atau air yang terkontaminasi. Juga melalui gigitan serangga penghisap darah.',
                'general_treatment' => 'Antibiotik dosis tinggi (penisilin, doksisiklin) pada tahap awal. Vaksinasi untuk hewan di daerah endemik.',
                'prevention_method' => 'Vaksinasi rutin di daerah endemik, pembakaran/penguburan bangkai yang benar, hindari membuka bangkai yang diduga anthrax.',
                'risk_factors' => 'Gembala di daerah endemik, tanah alkalin, banjir atau kekeringan yang mengganggu tanah.',
                'is_zoonotic' => 1,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 1,
                'is_viral' => 0,
                'image' => 'diseases/anthrax.jpg',
            ],
            [
                'name' => 'Rabies',
                'disease_code' => 'RAB-007',
                'causative_agent' => 'Virus Lyssavirus',
                'description' => 'Penyakit viral akut yang menyerang sistem saraf pusat, hampir selalu berakibat fatal. Menyebabkan perubahan perilaku, agresif, dan kelumpuhan.',
                'transmission_method' => 'Melalui air liur hewan yang terinfeksi, biasanya via gigitan.',
                'general_treatment' => 'Tidak ada pengobatan setelah gejala muncul. Vaksinasi pasca pajanan (PEP) sangat efektif jika diberikan segera setelah gigitan.',
                'prevention_method' => 'Vaksinasi wajib untuk anjing dan kucing, kontrol populasi hewan liar, edukasi masyarakat.',
                'risk_factors' => 'Gigitan hewan liar (anjing, kelelawar, rakun), hewan peliharaan tidak divaksin.',
                'is_zoonotic' => 1,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 0,
                'is_viral' => 1,
                'image' => 'diseases/rabies.jpg',
            ],
            [
                'name' => 'Parasitic Gastroenteritis (Cacingan)',
                'disease_code' => 'PGE-008',
                'causative_agent' => 'Nematoda (Cacing Gilik) - Haemonchus, Ostertagia, Trichostrongylus',
                'description' => 'Infeksi cacing pada saluran pencernaan yang menyebabkan diare, anemia, penurunan berat badan, dan produksi susu yang rendah.',
                'transmission_method' => 'Melalui pakan atau air yang terkontaminasi larva cacing.',
                'general_treatment' => 'Pemberian obat cacing (antelmintik) spektrum luas seperti ivermectin, albendazole.',
                'prevention_method' => 'Program deworming rutin, rotasi padang penggembalaan, manajemen kotoran yang baik.',
                'risk_factors' => 'Kepadatan ternak tinggi, padang rumput lembab, sanitasi buruk.',
                'is_zoonotic' => 0,
                'is_active' => 1,
                'is_parasite' => 1,
                'is_bakterial' => 0,
                'is_viral' => 0,
                'image' => 'diseases/worms.jpg',
            ],
            [
                'name' => 'Lumpy Skin Disease (LSD)',
                'disease_code' => 'LSD-009',
                'causative_agent' => 'Virus Capripoxvirus',
                'description' => 'Penyakit viral pada sapi yang ditandai dengan demam dan munculnya benjolan nodular pada kulit, membran mukosa, dan organ dalam.',
                'transmission_method' => 'Ditularkan terutama oleh vektor serangga penghisap darah (nyamuk, lalat).',
                'general_treatment' => 'Tidak ada pengobatan spesifik. Perawatan suportif untuk mencegah infeksi sekunder pada luka.',
                'prevention_method' => 'Vaksinasi, kontrol vektor serangga, pembatasan pergerakan hewan dari daerah wabah.',
                'risk_factors' => 'Musim hujan (banyak vektor), kepadatan ternak tinggi, tidak ada vaksinasi.',
                'is_zoonotic' => 0,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 0,
                'is_viral' => 1,
                'image' => 'diseases/lumpy-skin.jpg',
            ],
            [
                'name' => 'PPR (Peste des Petits Ruminants)',
                'disease_code' => 'PPR-010',
                'causative_agent' => 'Virus Morbillivirus',
                'description' => 'Penyakit viral yang sangat menular pada domba dan kambing. Menyebabkan demam tinggi, lesi mulut, diare parah, dan pneumonia.',
                'transmission_method' => 'Kontak langsung dengan hewan yang terinfeksi melalui droplet pernapasan atau sekresi lainnya.',
                'general_treatment' => 'Tidak ada pengobatan spesifik. Perawatan suportif untuk dehidrasi dan infeksi sekunder.',
                'prevention_method' => 'Vaksinasi yang sangat efektif, karantina hewan baru, isolasi hewan sakit.',
                'risk_factors' => 'Kontak di pasar hewan, kepadatan tinggi, sistem peternakan tradisional.',
                'is_zoonotic' => 0,
                'is_active' => 1,  
                'is_parasite' => 0,
                'is_bakterial' => 0,
                'is_viral' => 1,
                'image' => 'diseases/ppr.jpg',
            ],
            [
                'name' => 'African Swine Fever (ASF)',
                'disease_code' => 'ASF-011',
                'causative_agent' => 'Virus Asfivirus',
                'description' => 'Penyakit viral hemoragik yang sangat menular dan mematikan pada babi domestik dan liar. Tingkat kematian sangat tinggi (mendekati 100%).',
                'transmission_method' => 'Kontak langsung dengan babi sakit, melalui pakan yang terkontaminasi (sisa daging babi), vektor tungau, atau peralatan.',
                'general_treatment' => 'Tidak ada pengobatan atau vaksin. Depopulasi adalah satu-satunya cara mengontrol wabah.',
                'prevention_method' => 'Biosekuriti sangat ketat, tidak memberi pakan sisa daging babi, kontrol lalu lintas babi dan produknya.',
                'risk_factors' => 'Pemberian pakan sisa dapur, biosekuriti lemah, kontak dengan babi liar.',
                'is_zoonotic' => 0,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 0,
                'is_viral' => 1,
                'image' => 'diseases/asf.jpg',
            ],
            [
                'name' => 'Bovine Tuberculosis (TB Sapi)',
                'disease_code' => 'BTB-012',
                'causative_agent' => 'Bakteri Mycobacterium bovis',
                'description' => 'Penyakit kronis yang menyerang sistem pernapasan dan kelenjar limfa sapi, menyebabkan batuk, penurunan berat badan, dan pembengkakan kelenjar.',
                'transmission_method' => 'Melalui inhalasi droplet terinfeksi atau konsumsi susu yang terkontaminasi.',
                'general_treatment' => 'Pengobatan tidak dilakukan pada hewan karena alasan kesehatan masyarakat dan ekonomi. Hewan positif biasanya disembelih.',
                'prevention_method' => 'Uji tuberkulinasi rutin dan penyembelihan hewan reaktor, pasteurisasi susu.',
                'risk_factors' => 'Kepadatan tinggi dalam kandang tertutup, kontak dengan satwa liar (seperti badak) yang terinfeksi.',
                'is_zoonotic' => 1,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 1,
                'is_viral' => 0,
                'image' => 'diseases/tb-bovine.jpg',
            ],
            [
                'name' => 'Canine Parvovirus',
                'disease_code' => 'CPV-013',
                'causative_agent' => 'Virus Parvovirus',
                'description' => 'Penyakit viral yang sangat menular dan sering fatal pada anjing, terutama anak anjing. Menyebabkan muntah dan diare berdarah parah.',
                'transmission_method' => 'Kontak dengan feses anjing yang terinfeksi atau lingkungan yang terkontaminasi. Virus sangat stabil di lingkungan.',
                'general_treatment' => 'Perawatan suportif intensif: cairan infus, antibiotik, anti-muntah, dan nutrisi parenteral.',
                'prevention_method' => 'Vaksinasi anak anjing yang rutin dan ketat, desinfeksi area yang terkontamin dengan pemutih.',
                'risk_factors' => 'Anak anjing tidak divaksin, lingkungan dengan banyak anjing (kennel, shelter).',
                'is_zoonotic' => 0,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 0,
                'is_viral' => 1,
                'image' => 'diseases/parvo.jpg',
            ],
            [
                'name' => 'Fowl Cholera',
                'disease_code' => 'FC-014',
                'causative_agent' => 'Bakteri Pasteurella multocida',
                'description' => 'Penyakit bakterial pada unggas yang dapat bersifat akut atau kronis. Menyebabkan septikemia, pembengkakan wattles, dan artritis.',
                'transmission_method' => 'Melalui kontak dengan unggas sakit, melalui udara, atau konsumsi pakan/air yang terkontaminasi sekresi hidung/mulut.',
                'general_treatment' => 'Antibiotik seperti sulfonamides, tetrasiklin, atau enrofloxacin. Vaksinasi dapat digunakan di daerah endemik.',
                'prevention_method' => 'Biosekuriti, mengurangi stres, vaksinasi pada daerah wabah, sanitasi air minum.',
                'risk_factors' => 'Stres akibat transportasi atau cuaca buruk, unggas liar sebagai reservoir, sanitasi buruk.',
                'is_zoonotic' => 0,
                'is_active' => 1,
                'is_parasite' => 0,
                'is_bakterial' => 1,
                'is_viral' => 0,
                'image' => 'diseases/fowl-cholera.jpg',
            ],
            [
                'name' => 'Scabies (Kudis)',
                'disease_code' => 'SCA-015',
                'causative_agent' => 'Tungau Sarcoptes scabiei',
                'description' => 'Infestasi tungau yang menyebabkan gatal-gatal hebat, kerontokan bulu/rambut, dan penebalan kulit. Dapat menyerang berbagai hewan.',
                'transmission_method' => 'Kontak langsung dengan hewan atau lingkungan yang terkontaminasi tungau.',
                'general_treatment' => 'Aplikasi obat ectoparasiticide seperti ivermectin (suntik/topikal), selamectin, atau mandi belerang.',
                'prevention_method' => 'Menghindari kontak dengan hewan terinfeksi, treatment rutin untuk hewan baru, menjaga kebersihan kandang.',
                'risk_factors' => 'Kepadatan tinggi, kondisi kandang lembab dan kotor, hewan baru tanpa karantina.',
                'is_zoonotic' => 1, 
                'is_active' => 1,
                'is_parasite' => 1,
                'is_bakterial' => 0,
                'is_viral' => 0,
                'image' => 'diseases/scabies.jpg',
            ],

        ];

        // Insert data
        foreach ($diseases as $disease) {
            DB::table('diseases')->insertOrIgnore($disease);
        }
    }
}